<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Requestes\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JopApplicationPlatform.Domain\JopApplicationPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
